version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  CMAKE_BUILD_FOLDER: $(APPVEYOR_BUILD_FOLDER)/cmake
  CMAKE_GENERATOR: Visual Studio 15 2017
build_script:
- pwsh: '. "$Env:APPVEYOR_BUILD_FOLDER/build.ps1" -CMakeBuildFolder $Env:CMAKE_BUILD_FOLDER -Generator $Env:CMAKE_GENERATOR'
test_script:
- pwsh: '. "$Env:APPVEYOR_BUILD_FOLDER/test.ps1" -Root $Env:CMAKE_BUILD_FOLDER'