version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
environment:
  CMAKE_BUILD_FOLDER: $(APPVEYOR_BUILD_FOLDER)/cmake
  matrix:
  - CMAKE_GENERATOR: Visual Studio 15 2017
    CMAKE_CONFIG: release
  - CMAKE_GENERATOR: Visual Studio 15 2017
    CMAKE_CONFIG: debug
  - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_CONFIG: release
  - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_CONFIG: debug
  - CMAKE_GENERATOR: Visual Studio 15 2017 ARM
    CMAKE_CONFIG: release
  - CMAKE_GENERATOR: Visual Studio 15 2017 ARM
    CMAKE_CONFIG: debug
build_script:
- pwsh: '. "$Env:APPVEYOR_BUILD_FOLDER/build.ps1" -CMakeBuildFolder $Env:CMAKE_BUILD_FOLDER -Generator $Env:CMAKE_GENERATOR -Config $Env:CMAKE_CONFIG'
test_script:
- pwsh: '. "$Env:APPVEYOR_BUILD_FOLDER/test.ps1" -Root $Env:CMAKE_BUILD_FOLDER'